# Generated by Django 4.2.3 on 2023-07-25 12:59

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerRecords',
            fields=[
                ('primary_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('particulars', models.CharField(max_length=200)),
                ('folio', models.CharField(default='', max_length=100)),
                ('debit', models.FloatField(default=None)),
                ('credit', models.FloatField(default=None)),
                ('dr_or_cr', models.CharField(default='', max_length=100)),
                ('balance', models.FloatField(default=None)),
            ],
        ),
    ]
