# Generated by Django 4.2.3 on 2023-07-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HassanTradersApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LedgerRecords',
            new_name='LedgerRecord',
        ),
    ]
