# Generated by Django 4.2.3 on 2023-07-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HassanTradersApp', '0002_rename_ledgerrecords_ledgerrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerrecord',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ledgerrecord',
            name='credit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ledgerrecord',
            name='debit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ledgerrecord',
            name='dr_or_cr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerrecord',
            name='folio',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
