# Generated by Django 4.2.3 on 2023-07-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HassanTradersApp', '0003_alter_ledgerrecord_balance_alter_ledgerrecord_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerrecord',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerrecord',
            name='credit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerrecord',
            name='debit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerrecord',
            name='dr_or_cr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ledgerrecord',
            name='folio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
