# Generated by Django 4.2.3 on 2023-07-26 11:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HassanTradersApp', '0004_alter_ledgerrecord_balance_alter_ledgerrecord_credit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerUser',
            fields=[
                ('primary_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='ledgerrecord',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerrecord',
            name='credit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerrecord',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ledgerrecord',
            name='debit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgerrecord',
            name='user_id',
            field=models.ForeignKey(default=uuid.uuid4, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_records', to='HassanTradersApp.ledgeruser'),
        ),
    ]
