# Generated by Django 4.2.3 on 2023-07-26 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HassanTradersApp', '0005_ledgeruser_alter_ledgerrecord_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerrecord',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_records', to='HassanTradersApp.ledgeruser'),
        ),
    ]
