# Generated by Django 4.2.3 on 2023-07-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HassanTradersApp', '0006_alter_ledgerrecord_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeruser',
            name='client_type',
            field=models.CharField(choices=[('M', 'Company'), ('C', 'Customer')], default='C', max_length=1),
        ),
    ]
