# Generated by Django 4.2.3 on 2023-07-27 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HassanTradersApp', '0007_ledgeruser_client_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUser',
            fields=[
                ('primary_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('client_type', models.CharField(choices=[('M', 'Company'), ('C', 'Customer')], default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('primary_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('particulars', models.CharField(max_length=200)),
                ('bill_no', models.CharField(blank=True, default='', max_length=100)),
                ('receipt', models.IntegerField(blank=True, null=True)),
                ('issued', models.IntegerField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='HassanTradersApp.stockuser')),
            ],
        ),
    ]
