# Generated by Django 4.2.3 on 2023-08-01 14:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HassanTradersApp', '0008_stockuser_stockrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitUser',
            fields=[
                ('primary_key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('client_type', models.CharField(choices=[('M', 'Company'), ('C', 'Customer')], default='C', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='ledgerrecord',
            name='primary_key',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ledgeruser',
            name='primary_key',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='primary_key',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockuser',
            name='primary_key',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ProfitRecord',
            fields=[
                ('primary_key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('no_of_substance', models.CharField(max_length=200)),
                ('purchase', models.IntegerField(blank=True, null=True)),
                ('sale', models.IntegerField(blank=True, null=True)),
                ('diff', models.IntegerField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_records', to='HassanTradersApp.profituser')),
            ],
        ),
    ]
